name: RMurderMystery
version: '${project.version}'
main: ga.justreddy.wiki.rmurdermystery.MurderMystery
softdepend: [ PlaceholderAPI ]
depend:
  - Multiverse-Core
  - ProtocolLib
authors: [ JustReddy ]
description: MurderMystery plugin
commands:
  murdermystery:
    aliases:
      - mm